@echo off
set project=DJFlanger
set build_path=C:\Users\RudraMAC\Desktop\DjFlanger\DJFlanger\DspNetworks\Binaries
set msbuild="C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MsBuild.exe"
set vs_args=/p:Configuration="Release" /verbosity:minimal
set PreferredToolArchitecture=x64
set VisualStudioVersion=17.0

"C:\HISE-dabbu\tools\Projucer\Projucer.exe" --resave "%build_path%\AutogeneratedProject.jucer"

echo Compiling 64bit  %project% ...
set Platform=X64
%msbuild% "%build_path%\Builds\VisualStudio2022\%project%.sln" %vs_args%



pause
